name: Build and deploy Node.js app to Azure Web App - weatherapp-prod

on:
  push:
    branches: [ production ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install, build, test
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          npm run build --if-present
          npm test --if-present

      - name: Package deployable files
        run: |
          mkdir deploy
          cp package.json package-lock.json ./deploy || true
          cp -r server.js src public views dist ./deploy 2>/dev/null || true

      - uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_PROD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_PROD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_PROD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'weatherapp-prod'
          package: .
